### PR TITLE
Utility function for item valuation

### PR DESCRIPTION
**Pull request by C3ntraX**
Can you imporve the internal types? Would be nice

Maybe even with a description

/**
 * psv are: 1, 5, 7, 10, 12, 15, 18, 20, 25, 30, 40, 50, 70, 95, 99
 * what is PVS ....
 */

### CODE REVIEW

**Comment by zach-herridge** [comment]
Is this much different than https://github.com/PoeStack/poestack-sage/blob/main/src/echo-common/src/sage-valuation-service.ts#L18

**Comment by C3ntraX** [comment]
Oh didn't even see this function :/ hmm

**Comment by C3ntraX** [comment]
image

Where does the character or stash comes from?

image

image

**Comment by zach-herridge** [comment]
You never reference `EchoPoeItem` in your utility method like `withValuations` does so yours is just inferring the typing and it doesn't have any `character` or `stash` references. Even just using `withValuations` won't actually include a `character` or `stash` they would always be undefined. I inject those in the snapshot util methods I wrote if you aren't using those you need to inject those values yourself

**Comment by C3ntraX** [comment]
Yeah okay. I think we should emit the events through the pipeline and should't filter them. We should only filter events, which are not used like ratelimiting events for valuation.

Especially if you want to show error for api request failed like 400/500 etc. 
We may provide simple ready to use functions and function where you have to control it yourself.
Like withValuationFiltered and withValuation or something like this?

**Comment by zach-herridge** [comment]
Yeah I think that makes sense

**Comment by C3ntraX** [comment]
Better solution:
image


image
image
image

Instead of:
image

image
image

... Not neccesary: 
image

If we overwrite `result`, then we can correctly map the valuations for the item and omit the original `result`


Additional, I would get rid of 
`public withValuations(league: string, items: PoeItem[]): Observable<EchoPoeItem>` => `public withValuationsResultOnly(league: string, items: PoeItem[])` because the its just confusing with the character and stashtab. 
We may add add something like this if we want to pass additional informations:

```
export type <Meta>EchoPoeItem = {
   meta: Meta
}
```

**Comment by C3ntraX** [comment]
Why do we have two timestamps?

image

**Review by zach-herridge — APPROVED** [review]

**Pull request merged**
